=== kazieva/Task_03_3_parser/resources/xsd/vouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.kazieva.example.com/students"
        xmlns:tns="http://www.kazieva.example.com/students"
        elementFormDefault="qualified">
    <element name="tourist_vouchers">
        <complexType>
            <sequence>
                <element name="tourist_voucher"
                         type="tns:Tourist_voucher"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Tourist_voucher">
        <sequence>
            <element name="Type" type="tns:Type"/>
            <element name="NumberDays" type="positiveInteger"/>
            <element name="NumberNights" type="positiveInteger"/>
            <element name="Hotel" type="tns:Hotel"/>
            <element name="Cost" type="tns:Cost"/>
        </sequence>
        <attribute name="country" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="United Kingdom"/>
                    <enumeration value="France"/>
                    <enumeration value="Denmark"/>
                    <enumeration value="Netherlands"/>
                    <enumeration value="Lithuania"/>
                    <enumeration value="Bulgaria"/>
                    <enumeration value="China"/>
                    <enumeration value="South Korea"/>
                    <enumeration value="Japan"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="transport" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Airliner"/>
                    <enumeration value="Railway"/>
                    <enumeration value="Bus"/>
                    <enumeration value="Liner"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <simpleType name="Type">
        <restriction base="string">
            <enumeration value="holiday"/>
            <enumeration value="excursion"/>
            <enumeration value="recreation"/>
            <enumeration value="pilgrimage"/>
        </restriction>
    </simpleType>
    <complexType name="Hotel">
        <sequence>
            <element name="AmountOfStars" type="tns:Stars"/>
            <element name="AmountOfRoom" type="tns:HotelRoom"/>
        </sequence>
        <attribute name="name" use="required">
            <simpleType>
                <restriction base="ID">
                    <pattern value="[a-zA-Z0-9]{3,10}"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="food" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="HB"/>
                    <enumeration value="BB"/>
                    <enumeration value="AL"/>
                    <enumeration value="No"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="TV" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Yes"/>
                    <enumeration value="No"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="AirConditioning" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Yes"/>
                    <enumeration value="No"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="WiFi" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="Yes"/>
                    <enumeration value="No"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Cost">
        <sequence>
            <element name="price" type="tns:Price"/>
        </sequence>
        <attribute name="include" use="optional">
            <simpleType>
                <restriction base="string">
                    <enumeration value="SPA"/>
                    <enumeration value="Pool"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <simpleType name="Price">
        <restriction base="string">
            <pattern value="[0-9]{3,6}"/>
        </restriction>
    </simpleType>
    <simpleType name="Stars">
        <restriction base="positiveInteger">
            <pattern value="[1-5]"/>
        </restriction>
    </simpleType>
    <simpleType name="HotelRoom">
        <restriction base="positiveInteger">
            <pattern value="[1-3]"/>
        </restriction>
    </simpleType>
</schema>

=== kazieva/Task_03_3_parser/resources/xml/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tourist_vouchers  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xmlns="http://www.kazieva.example.com/students"
                   xsi:schemaLocation="http://www.example.com/students ../xsd/vouchers.xsd">
    <tourist_voucher country="Denmark" transport="Airliner">
        <Type>holiday</Type>
        <NumberDays>5</NumberDays>
        <NumberNights>7</NumberNights>
        <Hotel name="TheBest1" food="BB" TV="Yes">
            <AmountOfStars>4</AmountOfStars>
            <AmountOfRoom>2</AmountOfRoom>
        </Hotel>
        <Cost include="Pool">
            <price>200</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="Japan" transport="Airliner">
        <Type>excursion</Type>
        <NumberDays>2</NumberDays>
        <NumberNights>1</NumberNights>
        <Hotel name="TheBest2" food="AL" TV="Yes" WiFi="Yes">
            <AmountOfStars>3</AmountOfStars>
            <AmountOfRoom>1</AmountOfRoom>
        </Hotel>
        <Cost include="SPA">
            <price>300</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="France" transport="Railway">
        <Type>recreation</Type>
        <NumberDays>6</NumberDays>
        <NumberNights>7</NumberNights>
        <Hotel name="TheBest3" food="HB" AirConditioning="Yes">
            <AmountOfStars>5</AmountOfStars>
            <AmountOfRoom>3</AmountOfRoom>
        </Hotel>
        <Cost include="Pool">
            <price>1300</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="South Korea" transport="Airliner">
        <Type>recreation</Type>
        <NumberDays>8</NumberDays>
        <NumberNights>9</NumberNights>
        <Hotel name="TheBest4" food="BB" AirConditioning="Yes" TV="No" WiFi="Yes">
            <AmountOfStars>5</AmountOfStars>
            <AmountOfRoom>3</AmountOfRoom>
        </Hotel>
        <Cost include="Pool">
            <price>2000</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="Netherlands" transport="Liner">
        <Type>pilgrimage</Type>
        <NumberDays>3</NumberDays>
        <NumberNights>2</NumberNights>
        <Hotel name="TheBest5" food="AL">
            <AmountOfStars>2</AmountOfStars>
            <AmountOfRoom>1</AmountOfRoom>
        </Hotel>
        <Cost>
            <price>400</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="Denmark" transport="Bus">
        <Type>holiday</Type>
        <NumberDays>5</NumberDays>
        <NumberNights>6</NumberNights>
        <Hotel name="TheBest6" food="No" AirConditioning="No" TV="No" WiFi="No">
            <AmountOfStars>5</AmountOfStars>
            <AmountOfRoom>2</AmountOfRoom>
        </Hotel>
        <Cost include="SPA">
            <price>800</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="Bulgaria" transport="Railway">
        <Type>excursion</Type>
        <NumberDays>4</NumberDays>
        <NumberNights>4</NumberNights>
        <Hotel name="TheBest8" food="No" TV="Yes">
            <AmountOfStars>3</AmountOfStars>
            <AmountOfRoom>3</AmountOfRoom>
        </Hotel>
        <Cost>
            <price>700</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="Japan" transport="Airliner">
        <Type>holiday</Type>
        <NumberDays>14</NumberDays>
        <NumberNights>13</NumberNights>
        <Hotel name="TheBest9" food="AL" WiFi="Yes" AirConditioning="Yes" TV="Yes">
            <AmountOfStars>5</AmountOfStars>
            <AmountOfRoom>3</AmountOfRoom>
        </Hotel>
        <Cost include="SPA">
            <price>5000</price>
        </Cost>
    </tourist_voucher>
    <tourist_voucher country="France" transport="Bus">
        <Type>recreation</Type>
        <NumberDays>5</NumberDays>
        <NumberNights>5</NumberNights>
        <Hotel name="TheBest10" food="BB">
            <AmountOfStars>4</AmountOfStars>
            <AmountOfRoom>3</AmountOfRoom>
        </Hotel>
        <Cost include="Pool">
            <price>1000</price>
        </Cost>
    </tourist_voucher>
</tourist_vouchers>
